-- inserções das receitas:
INSERT INTO ingredients (id_ingredients, nome)
VALUES
(1, 'a.1. original sauce'),
(2, 'apple'),
(3, 'apple cider vinegar'),
(4, 'bacon'),
(5, 'baking soda'),
(6, 'bananas'),
(7, 'black pepper'),
(8, 'brown sugar'),
(9, 'burnet root'),
(10, 'butter'),
(11, 'cake flour'),
(12, 'cheddar cheese'),
(13, 'cheese'),
(14, 'chicken bouillon cubes'),
(15, 'chicken rice soup'),
(16, 'chili powder'),
(17, 'chocolate sandwich style cookies'),
(18, 'chocolate syrup'),
(19, 'cinnamon oil'),
(20, 'cinnamon sticks'),
(21, 'clove oil'),
(22, 'collard greens'),
(23, 'cornstarch'),
(24, 'cracked black pepper'),
(25, 'cumin'),
(26, 'dark brown sugar'),
(27, 'diced tomatoes'),
(28, 'dry mustard'),
(29, 'eggs'),
(30, 'extra virgin olive oil'),
(31, 'fennel seeds'),
(32, 'flour'),
(33, 'fresh cilantro leaves'),
(34, 'fresh coarse ground black pepper'),
(35, 'fresh garlic'),
(36, 'fresh ginger'),
(37, 'fresh lemon juice'),
(38, 'frozen apple juice concentrate'),
(39, 'garlic'),
(40, 'garlic powder'),
(41, 'gentian root'),
(42, 'great northern bean'),
(43, 'green olives'),
(44, 'ground beef'),
(45, 'ground cumin'),
(46, 'ham hock'),
(47, 'honey'),
(48, 'hot sauce'),
(49, 'kidney beans'),
(50, 'lean pork chops'),
(51, 'lettuce'),
(52, 'liquid smoke'),
(53, 'milk'),
(54, 'mirin'),
(55, 'molasses'),
(56, 'mustard powder'),
(57, 'new potatoes'),
(58, 'oil'),
(59, 'olive oil'),
(60, 'onion'),
(61, 'orange juice'),
(62, 'orange rind'),
(63, 'orange, juice of'),
(64, 'parsley'),
(65, 'pepper'),
(66, 'peppercorn'),
(67, 'pork spareribs'),
(68, 'powdered sugar'),
(69, 'prepared horseradish'),
(70, 'prepared pizza crust'),
(71, 'red bell pepper'),
(72, 'red chile'),
(73, 'red wine vinegar'),
(74, 'ripe olives'),
(75, 'rotel tomatoes'),
(76, 'salt'),
(77, 'salt and pepper'),
(78, 'sausage patty'),
(79, 'scullcap herb'),
(80, 'shallots'),
(81, 'sour cream'),
(82, 'soy sauce'),
(83, 'spearmint'),
(84, 'spreadable cheese with garlic and herbs'),
(85, 'strawberry'),
(86, 'strawberry ice cream'),
(87, 'sugar'),
(88, 'tarragon'),
(89, 'tomato juice'),
(90, 'tomato paste'),
(91, 'tomato sauce'),
(92, 'tomato soup'),
(93, 'unsalted butter'),
(94, 'vanilla ice cream'),
(95, 'vanilla wafers'),
(96, 'walnuts'),
(97, 'water'),
(98, 'whipped cream'),
(99, 'whipping cream'),
(100, 'whiskey'),
(101, 'white vinegar'),
(102, 'whole berry cranberry sauce'),
(103, 'wood bethony'),
(104, 'yellow bell pepper'),
(105, 'yellow onion'),
(106, 'yellow onions');

-- Inserção das receitas
INSERT INTO recipes (id_recipes, nome, tags, descricao, quantity)
VALUES
(1,"a bit different  breakfast pizza", "['30-minutes-or-less', 'time-to-make', 'course', 'main-ingredient', 'cuisine', 'preparation', 'occasion', 'north-american', 'breakfast', 'main-dish', 'pork', 'american', 'oven', 'easy', 'kid-friendly', 'pizza', 'dietary', 'northeastern-united-states', 'meat', 'equipment']", "this recipe calls for the crust to be prebaked a bit before adding ingredients. feel free to change sausage to ham or bacon. this warms well in the microwave for those late risers.", 6),
(2, "all in the kitchen chili", "['time-to-make', 'course', 'preparation', 'main-dish', 'chili', 'crock-pot-slow-cooker', 'dietary', 'equipment', '4-hours-or-less']", "this modified version of 'mom's' chili was a hit at our 2004 christmas party. we made an extra large pot to have some left to freeze but it never made it to the freezer. it was a favorite by all. perfect for any cold and rainy day. you won't find this one in a cookbook. it is truly an original.", 13),
(3, "alouette potatoes", "['60-minutes-or-less', 'time-to-make', 'course', 'main-ingredient', 'preparation', 'occasion', 'side-dishes', 'eggs-dairy', 'potatoes', 'vegetables', 'oven', 'easy', 'dinner-party', 'holiday-event', 'easter', 'cheese', 'stove-top', 'dietary', 'christmas', 'new-years', 'thanksgiving', 'independence-day', 'st-patricks-day', 'valentines-day', 'inexpensive', 'brunch', 'superbowl', 'equipment', 'presentation', 'served-hot']", "this is a super easy, great tasting, make ahead side dish that looks like you spent a lot more time preparing than you actually do. plus, most everything is done in advance. the times do not reflect the standing time of the potatoes.", 11),
(4, "amish tomato ketchup for canning", "['weeknight', 'time-to-make', 'course', 'main-ingredient', 'cuisine', 'preparation', 'occasion', 'north-american', 'canning', 'condiments-etc', 'vegetables', 'american', 'heirloom-historical', 'holiday-event', 'vegetarian', 'dietary', 'amish-mennonite', 'northeastern-united-states', 'number-of-servings', 'technique', '4-hours-or-less']", "my dh's amish mother raised him on this recipe. he much prefers it over store-bought ketchup. it was a taste i had to acquire, but now my ds's also prefer this type of ketchup. enjoy!", 8),
(5, "apple a day milk shake", "['15-minutes-or-less', 'time-to-make', 'course', 'main-ingredient', 'cuisine', 'preparation', 'occasion', 'north-american', 'low-protein', '5-ingredients-or-less', 'beverages', 'fruit', 'american', 'easy', 'kid-friendly', 'dietary', 'low-sodium', 'shakes', 'low-calorie', 'low-in-something', 'apples', 'number-of-servings', 'presentation', 'served-cold', '3-steps-or-less']", "", 4),
(6, "aww marinated olives", "['15-minutes-or-less', 'time-to-make', 'course', 'main-ingredient', 'cuisine', 'preparation', 'occasion', 'north-american', 'appetizers', 'fruit', 'canadian', 'dinner-party', 'vegan', 'vegetarian', 'freezer', 'dietary', 'equipment', 'number-of-servings']", "my italian mil was thoroughly impressed by my non-italian treatment of her olives. they are great appetizers and condiments to your fav pasta.(from the vancouver sun) ps. cook time include fridge time", 9),
(7, "backyard style barbecued ribs", "['weeknight', 'time-to-make', 'course', 'main-ingredient', 'cuisine', 'preparation', 'occasion', 'north-american', 'south-west-pacific', 'main-dish', 'pork', 'oven', 'holiday-event', 'stove-top', 'hawaiian', 'spicy', 'copycat', 'independence-day', 'meat', 'pork-ribs', 'super-bowl', 'novelty', 'taste-mood', 'savory', 'sweet', 'equipment', '4-hours-or-less']","this recipe is posted by request and was originaly from chef sam choy's cookbook", 22),
(8,"bananas 4 ice cream pie", "['weeknight', 'time-to-make', 'course', 'main-ingredient', 'preparation', 'pies-and-tarts', 'desserts', 'lunch', 'snacks', 'no-cook', 'refrigerator', 'kid-friendly', 'frozen-desserts', 'pies', 'chocolate', 'dietary', 'inexpensive', 'equipment', 'number-of-servings', 'technique', '4-hours-or-less']", "", 6),
(9, "beat this banana bread", "['weeknight', 'time-to-make', 'course', 'main-ingredient', 'preparation', 'occasion', 'breads', 'breakfast', 'fruit', 'oven', 'dietary', 'oamc-freezer-make-ahead', 'quick-breads', 'tropical-fruit', 'bananas', 'brunch', 'equipment', 'number-of-servings', '4-hours-or-less']", "from ann hodgman's", 9),
(10, "berry good sandwich spread", "['15-minutes-or-less', 'time-to-make', 'course', 'preparation', 'low-protein', 'healthy', '5-ingredients-or-less', 'condiments-etc', 'easy', 'dietary', 'low-sodium', 'low-in-something', '3-steps-or-less']", "horseradish is one of my favorite condiments as well as cranberry sauce. this is sweet and hot. i enjoy it on a smoked turkey & swiss sandwich, but also good alongside baked ham or roast beef.", 3),
(11, "better than sex strawberries", "['weeknight', 'time-to-make', 'course', 'main-ingredient', 'preparation', 'occasion', 'low-protein', 'pies-and-tarts', 'desserts', 'fruit', '1-day-or-more', 'pies', 'dietary', 'low-sodium', 'comfort-food', 'low-in-something', 'berries', 'strawberries', 'taste-mood']", "simple but sexy. this was in my local newspaper's food section. cook time reflects refrigeration time. i've been asked several times if this should be baked. just to clarify, no, it is not, it is a refrigerator dessert. i'm not sure why it contains raw egg, but most tiramisu recipes do too.", 7),
(12,"better then bush s baked beans", "['weeknight', 'time-to-make', 'course', 'main-ingredient', 'cuisine', 'preparation', 'occasion', 'north-american', 'side-dishes', 'beans', 'american', '1-day-or-more', 'oven', 'potluck', 'to-go', 'equipment']", "i'd have to say that this is a labor of love dish, but i give you my word that this recipe is better than bush's. enjoy! oh, and also this recipe is easily doubled. in fact, i think it turns out better when it is.", 13),
(13, "boat house collard greens", "['time-to-make', 'main-ingredient', 'preparation', 'vegetables', 'dietary', 'greens', 'collard-greens']", "my boss gave me this recipe several years ago. the recipe supposedly came from the", 7),
(14, "calm your nerves tonic", "['15-minutes-or-less', 'time-to-make', 'preparation', 'easy', 'number-of-servings']", "this will prove a blessing to everyone who takes it. it is soothing and relaxing, quieting to the nerves, has many good qualities, and is perfectly harmless. you can get the ingredients from any good health food store. you could up this to 1 cup each or lessen it to 1/8 cup each, according to your preference.",5),
(15, "chicken lickin good pork chops", "['weeknight', 'time-to-make', 'course', 'main-ingredient', 'preparation', 'main-dish', 'pork', 'crock-pot-slow-cooker', 'dietary', 'meat', 'pork-chops', 'equipment']", "here's and old standby i enjoy from time to time. it's from an old newspaper clipping i cut out years ago. very tasty.",7)
;